#!/usr/bin/env zsh

gruv_theme(){
  [[ -z $GRUV_PROMPT_FG ]]             && GRUV_PROMPT_FG=223
  [[ -z $GRUV_SECTION_EXIT_FG ]]       && GRUV_SECTION_EXIT_FG=234
  [[ -z $GRUV_SECTION_EXIT_BG ]]       && GRUV_SECTION_EXIT_BG=237
  [[ -z $GRUV_SECTION_EXIT_BG_ERROR ]] && GRUV_SECTION_EXIT_BG_ERROR=167
  [[ -z $GRUV_SECTION_TIME_FG ]]       && GRUV_SECTION_TIME_FG=223
  [[ -z $GRUV_SECTION_TIME_BG ]]       && GRUV_SECTION_TIME_BG=241
  [[ -z $GRUV_SECTION_BATTERY_FG ]]    && GRUV_SECTION_BATTERY_FG=239
  [[ -z $GRUV_SECTION_BATTERY_BG ]]    && GRUV_SECTION_BATTERY_BG=66
  [[ -z $GRUV_SECTION_USER_FG ]]       && GRUV_SECTION_USER_FG=239
  [[ -z $GRUV_SECTION_USER_BG ]]       && GRUV_SECTION_USER_BG=223
  [[ -z $GRUV_SECTION_PATH_FG ]]       && GRUV_SECTION_PATH_FG=223
  [[ -z $GRUV_SECTION_PATH_BG ]]       && GRUV_SECTION_PATH_BG=239
  [[ -z $GRUV_SECTION_VCS_BRANCH_FG ]] && GRUV_SECTION_VCS_BRANCH_FG=239
  [[ -z $GRUV_SECTION_VCS_BRANCH_BG ]] && GRUV_SECTION_VCS_BRANCH_BG=142
  [[ -z $GRUV_SECTION_VCS_STATUS_FG ]] && GRUV_SECTION_VCS_STATUS_FG=239
  [[ -z $GRUV_SECTION_VCS_STATUS_BG ]] && GRUV_SECTION_VCS_STATUS_BG=142
  [[ -z $GRUV_SECTION_VCS_DIRTY_FG ]]  && GRUV_SECTION_VCS_DIRTY_FG=239
  [[ -z $GRUV_SECTION_VCS_DIRTY_BG ]]  && GRUV_SECTION_VCS_DIRTY_BG=142
  [[ -z $GRUV_SECTION_SSH_FG ]]        && GRUV_SECTION_SSH_FG=223
  [[ -z $GRUV_SECTION_VENV_FG ]]       && GRUV_SECTION_VENV_FG=142
  [[ -z $GRUV_GIT_TRACKED_COLOR ]]     && GRUV_GIT_TRACKED_COLOR=66
  [[ -z $GRUV_GIT_UN_TRACKED_COLOR ]]  && GRUV_GIT_UN_TRACKED_COLOR=239
  [[ -z $GRUV_SECTION_VERSION_BG ]]    && GRUV_SECTION_VERSION_BG=235
  [[ -z $GRUV_PYTHON_COLOR ]]          && GRUV_PYTHON_COLOR=40
  [[ -z $GRUV_RUBY_COLOR ]]            && GRUV_RUBY_COLOR=196
  [[ -z $GRUV_JAVA_COLOR ]]            && GRUV_JAVA_COLOR=178
  [[ -z $GRUV_GO_COLOR ]]              && GRUV_GO_COLOR=81
  [[ -z $GRUV_ELIXIR_COLOR ]]          && GRUV_ELIXIR_COLOR=99
  [[ -z $GRUV_CRYSTAL_COLOR ]]         && GRUV_CRYSTAL_COLOR=8
  [[ -z $GRUV_NODE_COLOR ]]            && GRUV_NODE_COLOR=41
  [[ -z $GRUV_PHP_COLOR ]]             && GRUV_PHP_COLOR=57
}
